name: Build and Deploy Patch Release

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      app-dir: ./

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: pnpm/action-setup@v4
      with:
        version: 10
        registry-url: 'https://registry.npmjs.org'
        run_install: |
            - recursive: false
              args: [--frozen-lockfile, --strict-peer-dependencies]

    - run: pnpm ts
    - run: pnpm build
    - run: ls ./dist

    # release
    - run: git reset --hard
    - run: ls ./dist
      working-directory: ${{ env.app-dir }}
    - run: pnpm version patch  --git-tag-version false
    - name: commit version bump
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "bump version to $(node -p -e "require('./package.json').version") [skip ci]" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.OUR_GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
    - run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}