name: Build and Deploy Alpha Release

on:
  push:
    branches-ignore: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      app-dir: ./

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
        registry-url: 'https://registry.npmjs.org'
        run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

    - run: pnpm ts
    - run: pnpm build
    - run: ls ./dist

    # release
    - run: git reset --hard
    - run: ls ./dist
    - run: pnpm version prepatch --preid alpha-$GITHUB_RUN_NUMBER --git-tag-version false
    - run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}